### PR TITLE
working on refactoring partial

### PR DESCRIPTION
**Pull request by AbdullahAlger**

### CODE REVIEW

**Comment by AbdullahAlger** [comment]
@eliotsykes 
I am not sure why I am getting the following error on the edit page: 

`undefined local variable or method `sketch' for #<#<Class:0x007fff34c3d9b8>:0x007fff34c2f728>`

**Comment by AbdullahAlger** [comment]
@eliotsykes 

Forget it ... solved. Dumb question

**Comment by eliotsykes** [comment]
Nicely done! Did it feel good deleting that logic at the top of the _form partial?

**Comment by AbdullahAlger** [comment]
Yeah

**Pull request merged**
